# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CareerList',
        ),
    ]
