# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20160809_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerlist',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
