# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_careerlist_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerlist',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
